---

- hosts: all
  vars_files:
    - vars.yml
  remote_user: vagrant
  sudo: yes

  tasks:
    - name: copy maxim-colls
      action: copy src=./sites/maxim-colls dest=/var/www owner={{ user }} group=www-data

    - name: copy amics-del-ball
      action: copy src=./sites/amics-del-ball dest=/var/www owner={{ user }} group=www-data

    - name: ensure nginx is running
      service: name=nginx state=restarted
