---

- name: ensure /var/www exists
  action: file path=/var/www state=directory owner={{ user }} group=www-data

- name: remove default nginx site
  action: file path=/etc/nginx/sites-enabled/default state=absent

- name: write nginx sites available
  template: src=templates/nginx/{{ item }}.j2 dest=/etc/nginx/sites-available/{{ item }} mode=0644
  with_items: sites

- name: enable sites
  action: file src=/etc/nginx/sites-available/{{ item }} dest=/etc/nginx/sites-enabled/{{ item }} state=link
  with_items: sites

- name: ensure nginx is running
  service: name=nginx state=restarted
